### ISSUE TITLE
Wrong comment format

### ISSUE THREAD

**Issue by YahyaAlfayad** [DoctorOden/JavaScript.Module1#1]
https://github.com/DoctorOden/JO.JS/blob/aca17e829c292a13ba07540be4fa16c122f20e1f/Week4%20HW2.js#L1

Comments in JavaScript are either `//` for single line comments or `/*       */` for multi-line comments.

**Comment by DoctorOden** [comment]
I has move that file to other place: https://github.com/DoctorOden/JO.JS/blob/master/JavaScript1/Week2

I understand a problem and fix it, Thanks !
