### ISSUE TITLE
Most of your assignments are incorrect

### ISSUE THREAD

**Issue by Razpudding** [DoctorOden/JavaScript.Module1#12]
It looks like you're guessing how to do things. Did you do the free code camp assignments? They should make the homework a lot easier to do.

With almost every piece of code you write you seem to add mistakes to it, like this if statement
```
if (vehicleType1 === vehicleType2, true) 
	console.log("Red Car")
```
Where did you get the idea to add ",true"? I'm sure it's not in the materials we provided. Try not to guess what the answer  might be, but instead to create it from the materials we provide.

**Comment by DoctorOden** [comment]
I try, I cant recall all information from a head and search things from a web and try to combine then and make my home work otherwise its take month!
