### ISSUE TITLE
Make sure there are no syntax errors in your code before handing it in.

### ISSUE THREAD

**Issue by Razpudding** [DoctorOden/JavaScript.Module1#13]
If you cannot solve an assignment, just leave the code as it is but turn it into a code comment like so

```
/* This code doesnt work
function claculateSum(a,b,c){
    print(abc);
*/
```
And also try to run the code before you go to te next assignment. It looks like you wrote code but didnt check to see if it would work.

**Comment by DoctorOden** [comment]
ok i will. i just try to type but mostofly time i get bad code(
