### ISSUE TITLE
same variable declared twice

### ISSUE THREAD

**Issue by YahyaAlfayad** [DoctorOden/JavaScript.Module1#2]
https://github.com/DoctorOden/JO.JS/blob/aca17e829c292a13ba07540be4fa16c122f20e1f/Week4%20HW2.js#L5

since both declarations of x are in the same scope, this will result in an error that the same variable is declared twice.

**Comment by DoctorOden** [comment]
I think that is right now =
    let x = 7.25;
    math.round(x);

file link: https://github.com/DoctorOden/JO.JS/blob/master/JavaScript1/Week2
