### ISSUE TITLE
The html structure is a mess

### ISSUE THREAD

**Issue by Razpudding** [DoctorOden/JavaScript.Module1#20]
Instead of creating one ul and adding a li for each book, you seem to be adding a ul and then adding lis for each piece of information about a book randomly to the body. The lis are not being added to the ul...

Also assignment is a bad function name

**Comment by DoctorOden** [comment]
i change a name of assingment, but about that thing with ul and li was for me piece of really hard cakce, when i get more time i try to remastered some of my home works !
