### ISSUE TITLE
Math object starts with capital letter

### ISSUE THREAD

**Issue by YahyaAlfayad** [DoctorOden/JavaScript.Module1#3]
https://github.com/DoctorOden/JO.JS/blob/aca17e829c292a13ba07540be4fa16c122f20e1f/Week4%20HW2.js#L6

Since JS is case sensitive language, `Math` object must start with capital M otherwise this will produce an error that math is not defined.

**Comment by YahyaAlfayad** [comment]
Also needs `console.log()` call here to print the result otherwise it will be just calculated without any use of it.

**Comment by DoctorOden** [comment]
Done, i correct my home, hope that is right now
