### ISSUE TITLE
Wrong use of if statement

### ISSUE THREAD

**Issue by YahyaAlfayad** [DoctorOden/JavaScript.Module1#4]
https://github.com/DoctorOden/JO.JS/blob/aca17e829c292a13ba07540be4fa16c122f20e1f/Week4%20HW2.js#L19

`if` statement should be used with boolean check. In this case it must be used as:
```
if (typeof(x) == typeof(y)) {
```
Also there is no need to use reassignment inside if.

**Comment by DoctorOden** [comment]
that is ok now ? 

if (x == 9, y == "Hello") {
    console.log('SAME TYPE');
    }   

    else {
        console.log("OTHER");
    }
