### ISSUE TITLE
need a comma between elements

### ISSUE THREAD

**Issue by YahyaAlfayad** [DoctorOden/JavaScript.Module1#5]
https://github.com/DoctorOden/JO.JS/blob/aca17e829c292a13ba07540be4fa16c122f20e1f/Week4%20HW2.js#L33

When defining arrays, you should separate elements of the array by commas.

**Comment by DoctorOden** [comment]
I made a changes but im not so sure if its right, coz i dont sure about commas beetween string and number (he's position at the line)
