### ISSUE TITLE
Some research is expected!

### ISSUE THREAD

**Issue by unmeshvrije** [DoctorOden/JavaScript.Module1#7]
You are expected to use for loops on bash to print "hello" multiple times.
I appreciate that you used commands we learned to copy files instead of using 'cp' command. (using 'cat' with clipboard was smart)
For the last part, you should do more research on how to get unique strings from two files and use some commands to perform the task

https://github.com/DoctorOden/JO.JS/blob/aca17e829c292a13ba07540be4fa16c122f20e1f/JavaScrip%20Week4%20HW%201#L94

**Comment by DoctorOden** [comment]
Can you please explain what should i do ? Coz i saw your backlight notice at my code but i dont get it what should i do :(
